# Generated by Django 5.0.6 on 2024-05-25 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SafariApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='safari_post',
            options={'ordering': ('-date',)},
        ),
    ]
